defmodule Collector.MedusaPredInput do
  @behaviour Collector.Feed

  @enforce_keys [
    :target_dt,
    :server_id,
    # Snapshot
    :player_id,
    :has_alliance?,
    # AggServer
    :server_days_from_start,
    :has_speed?,
    :speed,
    # AggPlayers
    :player_days_from_start,
    :estimated_tribe,
    ## Today's data
    :t_total_population,
    :t_population_increase,
    :t_population_increase_by_founded,
    :t_population_increase_by_conquered,
    :t_population_decrease,
    :t_population_decrease_by_conquered,
    :t_population_decrease_by_destroyed,
    :t_total_villages,
    :t_n_villages_with_population_increase,
    :t_n_villages_with_population_decrease,
    :t_n_villages_with_population_stuck,
    :t_new_village_founded,
    :t_new_village_conquered,
    :t_lost_village_conquered,
    :t_lost_village_destroyed,
  ]



  defstruct [
    :target_dt,
    :server_id,
    # Snapshot
    :player_id,
    :has_alliance?,
    # AggServer
    :server_days_from_start,
    :has_speed?,
    :speed,
    # AggPlayers
    :player_days_from_start,
    :estimated_tribe,
    ## Today's data
    :t_total_population,
    :t_population_increase,
    :t_population_increase_by_founded,
    :t_population_increase_by_conquered,
    :t_population_decrease,
    :t_population_decrease_by_conquered,
    :t_population_decrease_by_destroyed,
    :t_total_villages,
    :t_n_villages_with_population_increase,
    :t_n_villages_with_population_decrease,
    :t_n_villages_with_population_stuck,
    :t_new_village_founded,
    :t_new_village_conquered,
    :t_lost_village_conquered,
    :t_lost_village_destroyed,
    ## Today - 1 sample
    t_1_has_data?: 0, #Represents a boolean value as false
    t_1_has_increase?: 0, #Represents a boolean value as false
    t_1_time_difference_in_days: 0,
    t_1_total_population: 0,
    t_1_population_increase: 0,
    t_1_population_increase_by_founded: 0,
    t_1_population_increase_by_conquered: 0,
    t_1_population_decrease: 0,
    t_1_population_decrease_by_conquered: 0,
    t_1_population_decrease_by_destroyed: 0,
    t_1_total_villages: 0,
    t_1_n_villages_with_population_increase: 0,
    t_1_n_villages_with_population_decrease: 0,
    t_1_n_villages_with_population_stuck: 0,
    t_1_new_village_founded: 0,
    t_1_new_village_conquered: 0,
    t_1_lost_village_conquered: 0,
    t_1_lost_village_destroyed: 0,
    ## Today - 2 sample
    t_2_has_data?: 0, #Represents a boolean value as false
    t_2_has_increase?: 0, #Represents a boolean value as false
    t_2_time_difference_in_days: 0,
    t_2_total_population: 0,
    t_2_population_increase: 0,
    t_2_population_increase_by_founded: 0,
    t_2_population_increase_by_conquered: 0,
    t_2_population_decrease: 0,
    t_2_population_decrease_by_conquered: 0,
    t_2_population_decrease_by_destroyed: 0,
    t_2_total_villages: 0,
    t_2_n_villages_with_population_increase: 0,
    t_2_n_villages_with_population_decrease: 0,
    t_2_n_villages_with_population_stuck: 0,
    t_2_new_village_founded: 0,
    t_2_new_village_conquered: 0,
    t_2_lost_village_conquered: 0,
    t_2_lost_village_destroyed: 0,
    ## Today - 3 sample
    t_3_has_data?: 0, #Represents a boolean value as false
    t_3_has_increase?: 0, #Represents a boolean value as false
    t_3_time_difference_in_days: 0,
    t_3_total_population: 0,
    t_3_population_increase: 0,
    t_3_population_increase_by_founded: 0,
    t_3_population_increase_by_conquered: 0,
    t_3_population_decrease: 0,
    t_3_population_decrease_by_conquered: 0,
    t_3_population_decrease_by_destroyed: 0,
    t_3_total_villages: 0,
    t_3_n_villages_with_population_increase: 0,
    t_3_n_villages_with_population_decrease: 0,
    t_3_n_villages_with_population_stuck: 0,
    t_3_new_village_founded: 0,
    t_3_new_village_conquered: 0,
    t_3_lost_village_conquered: 0,
    t_3_lost_village_destroyed: 0,
    ## Today - 4 sample
    t_4_has_data?: 0, #Represents a boolean value as false
    t_4_has_increase?: 0, #Represents a boolean value as false
    t_4_time_difference_in_days: 0,
    t_4_total_population: 0,
    t_4_population_increase: 0,
    t_4_population_increase_by_founded: 0,
    t_4_population_increase_by_conquered: 0,
    t_4_population_decrease: 0,
    t_4_population_decrease_by_conquered: 0,
    t_4_population_decrease_by_destroyed: 0,
    t_4_total_villages: 0,
    t_4_n_villages_with_population_increase: 0,
    t_4_n_villages_with_population_decrease: 0,
    t_4_n_villages_with_population_stuck: 0,
    t_4_new_village_founded: 0,
    t_4_new_village_conquered: 0,
    t_4_lost_village_conquered: 0,
    t_4_lost_village_destroyed: 0,
    ## Today - 5 sample
    t_5_has_data?: 0, #Represents a boolean value as false
    t_5_has_increase?: 0, #Represents a boolean value as false
    t_5_time_difference_in_days: 0,
    t_5_total_population: 0,
    t_5_population_increase: 0,
    t_5_population_increase_by_founded: 0,
    t_5_population_increase_by_conquered: 0,
    t_5_population_decrease: 0,
    t_5_population_decrease_by_conquered: 0,
    t_5_population_decrease_by_destroyed: 0,
    t_5_total_villages: 0,
    t_5_n_villages_with_population_increase: 0,
    t_5_n_villages_with_population_decrease: 0,
    t_5_n_villages_with_population_stuck: 0,
    t_5_new_village_founded: 0,
    t_5_new_village_conquered: 0,
    t_5_lost_village_conquered: 0,
    t_5_lost_village_destroyed: 0,
    ## Today - 6 sample
    t_6_has_data?: 0, #Represents a boolean value as false
    t_6_has_increase?: 0, #Represents a boolean value as false
    t_6_time_difference_in_days: 0,
    t_6_total_population: 0,
    t_6_population_increase: 0,
    t_6_population_increase_by_founded: 0,
    t_6_population_increase_by_conquered: 0,
    t_6_population_decrease: 0,
    t_6_population_decrease_by_conquered: 0,
    t_6_population_decrease_by_destroyed: 0,
    t_6_total_villages: 0,
    t_6_n_villages_with_population_increase: 0,
    t_6_n_villages_with_population_decrease: 0,
    t_6_n_villages_with_population_stuck: 0,
    t_6_new_village_founded: 0,
    t_6_new_village_conquered: 0,
    t_6_lost_village_conquered: 0,
    t_6_lost_village_destroyed: 0,
    ## Today - 7 sample
    t_7_has_data?: 0, #Represents a boolean value as false
    t_7_has_increase?: 0, #Represents a boolean value as false
    t_7_time_difference_in_days: 0,
    t_7_total_population: 0,
    t_7_population_increase: 0,
    t_7_population_increase_by_founded: 0,
    t_7_population_increase_by_conquered: 0,
    t_7_population_decrease: 0,
    t_7_population_decrease_by_conquered: 0,
    t_7_population_decrease_by_destroyed: 0,
    t_7_total_villages: 0,
    t_7_n_villages_with_population_increase: 0,
    t_7_n_villages_with_population_decrease: 0,
    t_7_n_villages_with_population_stuck: 0,
    t_7_new_village_founded: 0,
    t_7_new_village_conquered: 0,
    t_7_lost_village_conquered: 0,
    t_7_lost_village_destroyed: 0
  ]


  @type t :: %__MODULE__{
    target_dt: DateTime.t(),
    server_id: TTypes.server_id(),
    player_id: TTypes.player_id(),
    has_alliance?: non_neg_integer(),
    # AggServer
    server_days_from_start: non_neg_integer(),
    has_speed?: non_neg_integer(),
    speed: non_neg_integer(),
    # AggPlayers
    player_days_from_start: non_neg_integer(),
    estimated_tribe: TTypes.tribe_integer(),
    ## Today's data
    t_total_population: non_neg_integer(),
    t_population_increase: non_neg_integer(),
    t_population_increase_by_founded: non_neg_integer(),
    t_population_increase_by_conquered: non_neg_integer(),
    t_population_decrease: non_neg_integer(),
    t_population_decrease_by_conquered: non_neg_integer(),
    t_population_decrease_by_destroyed: non_neg_integer(),
    t_total_villages: pos_integer(),
    t_n_villages_with_population_increase: non_neg_integer(),
    t_n_villages_with_population_decrease: non_neg_integer(),
    t_n_villages_with_population_stuck: non_neg_integer(),
    t_new_village_founded: non_neg_integer(),
    t_new_village_conquered: non_neg_integer(),
    t_lost_village_conquered: non_neg_integer(),
    t_lost_village_destroyed: non_neg_integer(),
    ## Today - 1 sample
    t_1_has_data?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_1_has_increase?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_1_time_difference_in_days: non_neg_integer(),
    t_1_total_population: non_neg_integer(),
    t_1_population_increase: non_neg_integer(),
    t_1_population_increase_by_founded: non_neg_integer(),
    t_1_population_increase_by_conquered: non_neg_integer(),
    t_1_population_decrease: non_neg_integer(),
    t_1_population_decrease_by_conquered: non_neg_integer(),
    t_1_population_decrease_by_destroyed: non_neg_integer(),
    t_1_total_villages: non_neg_integer(),
    t_1_n_villages_with_population_increase: non_neg_integer(),
    t_1_n_villages_with_population_decrease: non_neg_integer(),
    t_1_n_villages_with_population_stuck: non_neg_integer(),
    t_1_new_village_founded: non_neg_integer(),
    t_1_new_village_conquered: non_neg_integer(),
    t_1_lost_village_conquered: non_neg_integer(),
    t_1_lost_village_destroyed: non_neg_integer(),
    ## Today - 2 sample
    t_2_has_data?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_2_has_increase?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_2_time_difference_in_days: non_neg_integer(),
    t_2_total_population: non_neg_integer(),
    t_2_population_increase: non_neg_integer(),
    t_2_population_increase_by_founded: non_neg_integer(),
    t_2_population_increase_by_conquered: non_neg_integer(),
    t_2_population_decrease: non_neg_integer(),
    t_2_population_decrease_by_conquered: non_neg_integer(),
    t_2_population_decrease_by_destroyed: non_neg_integer(),
    t_2_total_villages: non_neg_integer(),
    t_2_n_villages_with_population_increase: non_neg_integer(),
    t_2_n_villages_with_population_decrease: non_neg_integer(),
    t_2_n_villages_with_population_stuck: non_neg_integer(),
    t_2_new_village_founded: non_neg_integer(),
    t_2_new_village_conquered: non_neg_integer(),
    t_2_lost_village_conquered: non_neg_integer(),
    t_2_lost_village_destroyed: non_neg_integer(),
    ## Today - 3 sample
    t_3_has_data?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_3_has_increase?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_3_time_difference_in_days: non_neg_integer(),
    t_3_total_population: non_neg_integer(),
    t_3_population_increase: non_neg_integer(),
    t_3_population_increase_by_founded: non_neg_integer(),
    t_3_population_increase_by_conquered: non_neg_integer(),
    t_3_population_decrease: non_neg_integer(),
    t_3_population_decrease_by_conquered: non_neg_integer(),
    t_3_population_decrease_by_destroyed: non_neg_integer(),
    t_3_total_villages: non_neg_integer(),
    t_3_n_villages_with_population_increase: non_neg_integer(),
    t_3_n_villages_with_population_decrease: non_neg_integer(),
    t_3_n_villages_with_population_stuck: non_neg_integer(),
    t_3_new_village_founded: non_neg_integer(),
    t_3_new_village_conquered: non_neg_integer(),
    t_3_lost_village_conquered: non_neg_integer(),
    t_3_lost_village_destroyed: non_neg_integer(),
    ## Today - 4 sample
    t_4_has_data?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_4_has_increase?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_4_time_difference_in_days: non_neg_integer(),
    t_4_total_population: non_neg_integer(),
    t_4_population_increase: non_neg_integer(),
    t_4_population_increase_by_founded: non_neg_integer(),
    t_4_population_increase_by_conquered: non_neg_integer(),
    t_4_population_decrease: non_neg_integer(),
    t_4_population_decrease_by_conquered: non_neg_integer(),
    t_4_population_decrease_by_destroyed: non_neg_integer(),
    t_4_total_villages: non_neg_integer(),
    t_4_n_villages_with_population_increase: non_neg_integer(),
    t_4_n_villages_with_population_decrease: non_neg_integer(),
    t_4_n_villages_with_population_stuck: non_neg_integer(),
    t_4_new_village_founded: non_neg_integer(),
    t_4_new_village_conquered: non_neg_integer(),
    t_4_lost_village_conquered: non_neg_integer(),
    t_4_lost_village_destroyed: non_neg_integer(),
    ## Today - 5 sample
    t_5_has_data?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_5_has_increase?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_5_time_difference_in_days: non_neg_integer(),
    t_5_total_population: non_neg_integer(),
    t_5_population_increase: non_neg_integer(),
    t_5_population_increase_by_founded: non_neg_integer(),
    t_5_population_increase_by_conquered: non_neg_integer(),
    t_5_population_decrease: non_neg_integer(),
    t_5_population_decrease_by_conquered: non_neg_integer(),
    t_5_population_decrease_by_destroyed: non_neg_integer(),
    t_5_total_villages: non_neg_integer(),
    t_5_n_villages_with_population_increase: non_neg_integer(),
    t_5_n_villages_with_population_decrease: non_neg_integer(),
    t_5_n_villages_with_population_stuck: non_neg_integer(),
    t_5_new_village_founded: non_neg_integer(),
    t_5_new_village_conquered: non_neg_integer(),
    t_5_lost_village_conquered: non_neg_integer(),
    t_5_lost_village_destroyed: non_neg_integer(),
    ## Today - 6 sample
    t_6_has_data?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_6_has_increase?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_6_time_difference_in_days: non_neg_integer(),
    t_6_total_population: non_neg_integer(),
    t_6_population_increase: non_neg_integer(),
    t_6_population_increase_by_founded: non_neg_integer(),
    t_6_population_increase_by_conquered: non_neg_integer(),
    t_6_population_decrease: non_neg_integer(),
    t_6_population_decrease_by_conquered: non_neg_integer(),
    t_6_population_decrease_by_destroyed: non_neg_integer(),
    t_6_total_villages: non_neg_integer(),
    t_6_n_villages_with_population_increase: non_neg_integer(),
    t_6_n_villages_with_population_decrease: non_neg_integer(),
    t_6_n_villages_with_population_stuck: non_neg_integer(),
    t_6_new_village_founded: non_neg_integer(),
    t_6_new_village_conquered: non_neg_integer(),
    t_6_lost_village_conquered: non_neg_integer(),
    t_6_lost_village_destroyed: non_neg_integer(),
    ## Today - 7 sample
    t_7_has_data?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_7_has_increase?: non_neg_integer(), #Represents a boolean value as 0 or 1
    t_7_time_difference_in_days: non_neg_integer(),
    t_7_total_population: non_neg_integer(),
    t_7_population_increase: non_neg_integer(),
    t_7_population_increase_by_founded: non_neg_integer(),
    t_7_population_increase_by_conquered: non_neg_integer(),
    t_7_population_decrease: non_neg_integer(),
    t_7_population_decrease_by_conquered: non_neg_integer(),
    t_7_population_decrease_by_destroyed: non_neg_integer(),
    t_7_total_villages: non_neg_integer(),
    t_7_n_villages_with_population_increase: non_neg_integer(),
    t_7_n_villages_with_population_decrease: non_neg_integer(),
    t_7_n_villages_with_population_stuck: non_neg_integer(),
    t_7_new_village_founded: non_neg_integer(),
    t_7_new_village_conquered: non_neg_integer(),
    t_7_lost_village_conquered: non_neg_integer(),
    t_7_lost_village_destroyed: non_neg_integer()
        }

end
