name: On master merge

on:
  push:
    branches: [ "master" ]

jobs:
  update_version:
    name: Update the version file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            version.txt
          sparse-checkout-cone-mode: false

      - name: Read and update the version file
        run: python3 .github/update_version.py

      - name: Commit and push change
        run: |
          git config --global user.name "your username"
          git config --global user.email "your email"
          git add -A
          git commit -m "update version"
          git push
